# Generated by Django 3.2.9 on 2021-12-14 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0002_productsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessiondId', models.CharField(max_length=255, null=True)),
                ('serviceCode', models.CharField(max_length=255, null=True)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('names', models.CharField(max_length=255)),
                ('size', models.IntegerField(max_length=255)),
                ('paymentMode', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Idafarmuser',
        ),
        migrations.DeleteModel(
            name='Productsmodel',
        ),
    ]
